// Injects the SEO head block (canonical, hreflang, Open Graph, Twitter, icons) and the
// JSON-LD graph into both language pages, and writes robots.txt / sitemap.xml /
// site.webmanifest. The FAQ entities are read back out of the markup so the structured
// data can never drift from the visible answers — re-run after editing the FAQ.
import fs from 'fs';

const ORIGIN = 'https://doverka.eu';

const PAGES = {
  'index.html': {
    lang: 'uk',
    locale: 'uk_UA',
    altLocale: 'ru_RU',
    path: '/',
    og: 'images/og-cover.jpg',
    title: 'Нотаріальні документи для України з апостилем | Doverka.eu',
    desc: 'Довіреність, заява та інші документи для України для українців у Швеції та ЄС. Онлайн‑підписання з нотаріусом, апостиль у Стокгольмі, доставка в Україну.',
    imageAlt: 'Doverka.eu — нотаріальні документи для України онлайн, з апостилем',
    orgDesc: 'Нотаріальні документи українською з апостилем для українців у Швеції та країнах ЄС: підготовка тексту, онлайн‑підписання з нотаріусом, апостиль у Стокгольмі та доставка в Україну.',
    person: { name: 'Богдан Гребенюк', jobTitle: 'Адвокат' },
    offers: [
      { name: 'Документ під ключ', desc: 'Консультація, підготовка документа українською, підписання з нотаріусом, засвідчення підпису та апостиль у Стокгольмі.', price: '2350' },
      { name: 'Доставка в Україну', desc: 'Відправка оригіналу Новою поштою з номером накладної для відстеження.', price: '400' },
      { name: 'Представництво в Україні', desc: 'Адвокат у вашому місті в Україні: нотаріус, банк, податкова, реєстри, звіт про виконану роботу.', price: '1100', from: true },
    ],
  },
  'ru.html': {
    lang: 'ru',
    locale: 'ru_RU',
    altLocale: 'uk_UA',
    path: '/ru.html',
    og: 'images/og-cover-ru.jpg',
    title: 'Нотариальные документы для Украины с апостилем | Doverka.eu',
    desc: 'Доверенность, заявление и другие документы для Украины для украинцев в Швеции и ЕС. Онлайн‑подписание с нотариусом, апостиль в Стокгольме, доставка в Украину.',
    imageAlt: 'Doverka.eu — нотариальные документы для Украины онлайн, с апостилем',
    orgDesc: 'Нотариальные документы на украинском языке с апостилем для украинцев в Швеции и странах ЕС: подготовка текста, онлайн‑подписание с нотариусом, апостиль в Стокгольме и доставка в Украину.',
    person: { name: 'Богдан Гребенюк', jobTitle: 'Адвокат' },
    offers: [
      { name: 'Документ под ключ', desc: 'Консультация, подготовка документа на украинском, подписание с нотариусом, заверение подписи и апостиль в Стокгольме.', price: '2350' },
      { name: 'Доставка в Украину', desc: 'Отправка оригинала Новой почтой с номером накладной для отслеживания.', price: '400' },
      { name: 'Представительство в Украине', desc: 'Адвокат в вашем городе в Украине: нотариус, банк, налоговая, реестры, отчёт о проделанной работе.', price: '1100', from: true },
    ],
  },
};

const MARK_OPEN = '<!-- ===== SEO / social / icons — generated by build-seo.mjs ===== -->';
const MARK_CLOSE = '<!-- ===== /SEO ===== -->';
const LD_OPEN = '<!-- ===== structured data — generated by build-seo.mjs ===== -->';
const LD_CLOSE = '<!-- ===== /structured data ===== -->';

const stripTags = s => s.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const decode = s => s.replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"');
const attr = s => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// pull the visible FAQ straight out of the page
function readFaq(html) {
  const items = [];
  const re = /<button class="faq__q"[^>]*>([\s\S]*?)<span class="faq__ic"[\s\S]*?<div class="faq__a"><div>([\s\S]*?)<\/div><\/div>/g;
  let m;
  while ((m = re.exec(html))) {
    items.push({ q: decode(stripTags(m[1])), a: decode(stripTags(m[2])) });
  }
  return items;
}

function head(p) {
  const url = ORIGIN + p.path;
  const img = `${ORIGIN}/${p.og}`;
  return `${MARK_OPEN}
<link rel="canonical" href="${url}">
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1">
<meta name="author" content="${attr(p.person.name)}">

<link rel="alternate" hreflang="uk" href="${ORIGIN}/">
<link rel="alternate" hreflang="ru" href="${ORIGIN}/ru.html">
<link rel="alternate" hreflang="x-default" href="${ORIGIN}/">

<!-- Open Graph. og:image is the brand card, never the portrait — a shared link has to
     read as doverka.eu at thumbnail size. Regenerate it with gen-og.mjs. -->
<meta property="og:type" content="website">
<meta property="og:site_name" content="Doverka.eu">
<meta property="og:locale" content="${p.locale}">
<meta property="og:locale:alternate" content="${p.altLocale}">
<meta property="og:url" content="${url}">
<meta property="og:title" content="${attr(p.title)}">
<meta property="og:description" content="${attr(p.desc)}">
<meta property="og:image" content="${img}">
<meta property="og:image:secure_url" content="${img}">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${attr(p.imageAlt)}">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${attr(p.title)}">
<meta name="twitter:description" content="${attr(p.desc)}">
<meta name="twitter:image" content="${img}">
<meta name="twitter:image:alt" content="${attr(p.imageAlt)}">

<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="apple-mobile-web-app-title" content="Doverka.eu">
<meta name="theme-color" content="#1f477b">
${MARK_CLOSE}`;
}

function jsonld(p, faq) {
  const url = ORIGIN + p.path;
  const graph = [
    {
      '@type': 'WebSite',
      '@id': `${ORIGIN}/#website`,
      url: `${ORIGIN}/`,
      name: 'Doverka.eu',
      inLanguage: p.lang,
      publisher: { '@id': `${ORIGIN}/#organization` },
    },
    {
      '@type': ['LegalService', 'ProfessionalService'],
      '@id': `${ORIGIN}/#organization`,
      name: 'Doverka.eu',
      alternateName: 'Doverka',
      url: `${ORIGIN}/`,
      description: p.orgDesc,
      logo: {
        '@type': 'ImageObject',
        '@id': `${ORIGIN}/#logo`,
        url: `${ORIGIN}/icon-512.png`,
        contentUrl: `${ORIGIN}/icon-512.png`,
        width: 512,
        height: 512,
        caption: 'Doverka.eu',
      },
      image: { '@id': `${ORIGIN}/#logo` },
      telephone: ['+46736784546', '+380677357000'],
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'Drottninggatan 32, 11tr',
        postalCode: '111 51',
        addressLocality: 'Stockholm',
        addressCountry: 'SE',
      },
      openingHoursSpecification: [
        { '@type': 'OpeningHoursSpecification', dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], opens: '09:00', closes: '17:00' },
      ],
      areaServed: [
        { '@type': 'Country', name: 'Sweden' },
        { '@type': 'Country', name: 'Ukraine' },
        { '@type': 'Place', name: 'European Union' },
      ],
      availableLanguage: [
        { '@type': 'Language', name: 'Ukrainian', alternateName: 'uk' },
        { '@type': 'Language', name: 'Russian', alternateName: 'ru' },
      ],
      priceRange: '400–2350 SEK',
      currenciesAccepted: 'SEK',
      founder: { '@id': `${ORIGIN}/#bogdan` },
      provider: { '@id': `${ORIGIN}/#bogdan` },
      sameAs: [
        'https://t.me/BogdanGrebenyuk',
        'https://www.instagram.com/doverka_eu/',
        'https://testimonial.to/doverka',
      ],
      hasOfferCatalog: {
        '@type': 'OfferCatalog',
        name: p.lang === 'uk' ? 'Послуги Doverka.eu' : 'Услуги Doverka.eu',
        itemListElement: p.offers.map(o => ({
          '@type': 'Offer',
          name: o.name,
          description: o.desc,
          price: o.price,
          priceCurrency: 'SEK',
          ...(o.from ? { priceSpecification: { '@type': 'PriceSpecification', minPrice: o.price, priceCurrency: 'SEK' } } : {}),
          availability: 'https://schema.org/InStock',
          url,
        })),
      },
    },
    {
      '@type': 'Person',
      '@id': `${ORIGIN}/#bogdan`,
      name: p.person.name,
      jobTitle: p.person.jobTitle,
      image: `${ORIGIN}/images/bogdan-portrait.jpg`,
      url,
      worksFor: { '@id': `${ORIGIN}/#organization` },
      workLocation: {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          streetAddress: 'Drottninggatan 32, 11tr',
          postalCode: '111 51',
          addressLocality: 'Stockholm',
          addressCountry: 'SE',
        },
      },
      sameAs: [
        'https://www.facebook.com/bogdan.grebenyuk',
        'https://t.me/BogdanGrebenyuk',
      ],
    },
    {
      '@type': 'WebPage',
      '@id': `${url}#webpage`,
      url,
      name: p.title,
      description: p.desc,
      inLanguage: p.lang,
      isPartOf: { '@id': `${ORIGIN}/#website` },
      about: { '@id': `${ORIGIN}/#organization` },
      primaryImageOfPage: { '@id': `${ORIGIN}/#logo` },
    },
  ];

  if (faq.length) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${url}#faq`,
      inLanguage: p.lang,
      isPartOf: { '@id': `${url}#webpage` },
      mainEntity: faq.map(f => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    });
  }

  const json = JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2)
    .replace(/</g, '\\u003c');   // never let a stray "<" close the script early
  return `${LD_OPEN}\n<script type="application/ld+json">\n${json}\n</script>\n${LD_CLOSE}`;
}

// ---- patch the pages -------------------------------------------------------
for (const [file, p] of Object.entries(PAGES)) {
  let html = fs.readFileSync(file, 'utf8');
  const faq = readFaq(html);

  // drop the previously generated blocks and the old relative hreflang trio
  html = html.replace(new RegExp(`${MARK_OPEN}[\\s\\S]*?${MARK_CLOSE}\\n?`), '');
  html = html.replace(new RegExp(`${LD_OPEN}[\\s\\S]*?${LD_CLOSE}\\n?`), '');
  html = html.replace(/<link rel="alternate" hreflang="(?:uk|ru|x-default)" href="\/(?:index|ru)\.html">\n?/g, '');

  html = html.replace(/(<meta name="description"[^>]*>\n)/, `$1\n${head(p)}\n`);
  html = html.replace(/(\n)?<\/head>/, `\n\n${jsonld(p, faq)}\n</head>`);

  fs.writeFileSync(file, html);
  console.log(`${file}: head block + JSON-LD (${faq.length} FAQ entries)`);
}

// ---- site files ------------------------------------------------------------
fs.writeFileSync('robots.txt', `User-agent: *
Allow: /

Sitemap: ${ORIGIN}/sitemap.xml
`);

const lastmod = process.env.LASTMOD || new Date().toISOString().slice(0, 10);
const alternates = `    <xhtml:link rel="alternate" hreflang="uk" href="${ORIGIN}/"/>
    <xhtml:link rel="alternate" hreflang="ru" href="${ORIGIN}/ru.html"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="${ORIGIN}/"/>`;

fs.writeFileSync('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>${ORIGIN}/</loc>
${alternates}
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${ORIGIN}/ru.html</loc>
${alternates}
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.9</priority>
  </url>
</urlset>
`);

fs.writeFileSync('site.webmanifest', JSON.stringify({
  name: 'Doverka.eu — нотаріальні документи для України',
  short_name: 'Doverka.eu',
  description: PAGES['index.html'].orgDesc,
  lang: 'uk',
  dir: 'ltr',
  start_url: '/',
  scope: '/',
  id: '/',
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#ffffff',
  theme_color: '#1f477b',
  icons: [
    { src: '/favicon.svg', type: 'image/svg+xml', sizes: 'any' },
    { src: '/icon-192.png', type: 'image/png', sizes: '192x192', purpose: 'any' },
    { src: '/icon-512.png', type: 'image/png', sizes: '512x512', purpose: 'any' },
    { src: '/icon-maskable-512.png', type: 'image/png', sizes: '512x512', purpose: 'maskable' },
  ],
}, null, 2) + '\n');

console.log('robots.txt, sitemap.xml, site.webmanifest written');
